
import os
 
print("                                                         ")
print("                  GAME  BY  @tomilefteri                 ")
print("                                                         ")
print("          ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░          ")
print("          ░▒▄▀▀▀▄░▒▀▀█▀▀░▒█▀▀▀█░▒█▀▀▀▄░▒▀▀█▀▀░░          ")
print("          ░▒█ ░░░░░░░█ ░░▒█ ░░█░▒█ ░░█░░░░█ ░░░          ")
print("          ░▒▀▄▄▄░░░░░█ ░░▒█■■■█░▒█▄▄▄▀░░░░█ ░░░          ")
print("          ░░░░░░█░░░░█ ░░▒█ ░░█░▒█▀▄░░░░░░█ ░░░          ")
print("          ░▒▀▄▄▄▀░░░░█ ░░▒█ ░░█░▒█ ░▀▄░░░░█ ░░░          ")
print("          ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░          ")
print("                                                         ")
print("                                                         ")
Begin = input("                  Press  z  to  Start!  ")
Begin = Begin.lower()

if Begin == "z":
  os.system("cls")
  print("                                                         ")
  print(" You were walking through the forest and then...         ")
  print(" You saw a tree that had a paper on it...                ")
  print("                                                         ")
  print("          _____                                          ")
  print("         /     \____                                     ")
  print("         \  ...     \                _____    ____       ")
  print("     ____/     ...  /__             / ... \  /    \      ")
  print("    /  ....  ...   ... \            \     /  \ .. /      ")
  print("    \_____       ______/         ___/  .. \__/    \      ")
  print("          |     |               /  ....  .... ...  \     ")
  print("          |     |               \______         ___/     ")
  print("          |     |                      |       |         ")
  print("          |     |                      |  ___  |         ")
  print("          |     |                      | |#$%| |         ")
  print("   ______/       \________             | |___| |         ")
  print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~           |       |         ")
  print("                               _______/         \______  ")
  print("                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
  print("                                                         ")
  a = input(" Press z to continue... or press x to go home... ") 
  a = a.lower()
  
  if a == "z":
    os.system("cls")
    print("                                                         ")
    print(" You took a look at the paper...                         ")
    print(" And you are thinking of what to do now...               ")     
    print("       ____________________________________________      ")
    print("      |                                            |     ")
    print("      |           TAKE  PART  AT  THIS!            |     ")
    print("      |                                            |     ")
    print("      | The first person to climb the tower will   |     ")
    print("      | get one wish of his/hers fulfilled         |     ")
    print("      |                                            |     ")
    print("      | Go to the tower and participate            |     ")
    print("      | You have nothing to lose and a lot to gain |     ")
    print("      |                                            |     ")
    print("      | The tower is at the fields of corn...      |     ")
    print("      |                                            |     ")
    print("      | DO NOT LOSE THIS OPPORTUNITY!              |     ")
    print("      |____________________________________________|     ")
    print("                                                         ")
    b = input(" Press z to continue... or press x to go home... ") 
    b = b.lower()
    
    if b == "z":
      os.system("cls")
      print("                                                         ")
      print(" You went to the fields and you saw the tower...         ")
      print("                                                         ")
      print("     ------     ---            /\         -----          ")
      print("       -----                  /~~\          -------      ")
      print("                    ----     /~~~~\                      ")
      print("    ------                  /~~~~~~\  ----       -----   ")
      print("                           /~~~~~~~~\                    ")
      print("            -----         /~~~~~~~~~~\        -----      ")
      print("                         /~~~~~~~~~~~~\                  ")
      print("                        [  _____       ]                 ")
      print("                        [  |-|-|       ]                 ")
      print("                        [  `````       ]                 ")
      print("                        [       _____  ]                 ")
      print("                        [       |-|-|  ]                 ")
      print("                        [       `````  ]                 ")
      print("          ___           [      ____    ]                 ")
      print("         /0 0\          [     | <> |   ]                 ")
      print("          -|-           [     |   *|   ]                 ")
      print("          / \           [_____|____|___]                 ")
      print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
      print("                                                         ")
      c = input(" Press z to continue... or press x to go home... ") 
      c = c.lower()
      
      if c == "z":
        os.system("cls")
        print("                                                         ")
        print(" You opened the door and...                              ") 
        print(" You see a paper on the floor...                         ") 
        print("  ____________________________________________________   ") 
        print(" |      1   |                        |__________|     |  ") 
        print(" |    1     |  1  1  1  1  1  1  1   |__________|  1  |  ") 
        print(" |  1   /|  |                        |__________|     |  ") 
        print(" |1    / |  |_______________________ |__________| ____|  ")
        print(" |    /  | /                         |__________|     |  ") 
        print(" |    | *|/             /|           |__________|     |  ") 
        print(" |    |  /   ____      / |           |__________|     |  ") 
        print(" |    | /   /$$#/     /  |           |__________|     |  ") 
        print(" |    |/   /___/         |           |__________|     |  ") 
        print(" |    /                  |           |__________|     |  ") 
        print(" |   /              -----------                       |  ") 
        print(" |  /                                                 |  ") 
        print(" | /                                                  |  ") 
        print(" |/___________________________________________________|  ") 
        print("                                                         ")
        d = input("Press z to read the paper...   Press x to go home... ") 
        d = d.lower()
        
        if d == "z":
          os.system("cls")
          print("                                                         ")
          print(" You took a look at the paper...                         ")
          print(" And you are thinking of what to do now...               ")     
          print("       ____________________________________________      ")
          print("      |                                            |     ")
          print("      |           WHO CARES FOR A WISH!            |     ")
          print("      |                                            |     ")
          print("      | Inside of this door is a mountain of gold, |     ")
          print("      | is so much that you could even by a world  |     ")
          print("      |                                            |     ")
          print("      | Why to go to the top when you can buy      |     ")
          print("      | anything that you wish?                    |     ")
          print("      |                                            |     ")
          print("      | I say endless wishes better than one!      |     ")
          print("      |                                            |     ")
          print("      | DO NOT LOSE THIS OPPORTUNITY!              |     ")
          print("      |____________________________________________|     ")
          print("                                                         ")
          e = input("Press c to open the door... Press z to go upstairs... Press x to go home... ") 
          e = e.lower()
          
          if e == "z":
            os.system("cls")
            print("                                                         ")
            print(" You have gone upstairs and you see in front of you...   ")
            print(" Another door and the stairs going up...                 ")
            print(" Wait there is also another letter in the ground...      ")
            print("  ____________________________________________________   ") 
            print(" |       2  |                        |__________|     |  ") 
            print(" |     2    |  2  2  2  2  2  2  2   |__________|  2  |  ") 
            print(" |   2  /|  |                        |__________|     |  ") 
            print(" | 2   / |  |_______________________ |__________| ____|  ")
            print(" |    / 2| /                         |__________|     |  ") 
            print(" |    | *|/           ______         |__________|     |  ") 
            print(" |    |  /   ___     /      \        |__________|     |  ") 
            print(" |    | /   /#%/     \     /         |__________|     |  ") 
            print(" |    |/   /__/          /         __|__________|___  |  ") 
            print(" |    /                /         |   |__________|   | |  ") 
            print(" |   /               /_______    |___|__________|___| |  ") 
            print(" |  /                                                 |  ") 
            print(" | /                                                  |  ") 
            print(" |/___________________________________________________|  ") 
            print("                                                         ")
            f = input("Press z to read the paper...   Press x to go home... ") 
            f = f.lower()
            
            if f == "z":
              os.system("cls")
              print("                                                         ")
              print(" You took a look at the paper...                         ")
              print(" And you are thinking of what to do now...               ")     
              print("       ____________________________________________      ")
              print("      |                                            |     ")
              print("      |           WHO CARES FOR A WISH!            |     ")
              print("      |                                            |     ")
              print("      | Inside of this door you gone find power,   |     ")
              print("      | you will be able to win everything         |     ")
              print("      |                                            |     ")
              print("      | Why to go to the top when you can win      |     ")
              print("      | anything that you wish by force?           |     ")
              print("      |                                            |     ")
              print("      | I say endless wishes better than one!      |     ")
              print("      |                                            |     ")
              print("      | DO NOT LOSE THIS OPPORTUNITY!              |     ")
              print("      |____________________________________________|     ")
              print("                                                         ")
              g = input("Press c to open the door... Press z to go upstairs... Press x to go home... ") 
              g = g.lower()
              
              if g == "z":
                os.system("cls")
                print("                                                         ")
                print(" You have gone upstairs and you see in front of you...   ")
                print(" Another door, the stairs going up and another paper...  ")
                print("  ____________________________________________________   ") 
                print(" |       3  |                        |__________|     |  ") 
                print(" |     3    |  3  3  3  3  3  3  3   |__________|  3  |  ") 
                print(" |   3  /|  |                        |__________|     |  ") 
                print(" | 3   / |  |_______________________ |__________| ____|  ")
                print(" |    / 3| /                         |__________|     |  ") 
                print(" |    | *|/                          |__________|     |  ") 
                print(" |    |  /  ___     _______          |__________|     |  ") 
                print(" |    | /  /&$/    /       \         |__________|     |  ") 
                print(" |    |/  /__/         ___ /      ___|__________|___  |  ") 
                print(" |    /                    \     |   |__________|   | |  ") 
                print(" |   /             \_______/     |___|__________|___| |  ") 
                print(" |  /                                                 |  ") 
                print(" | /                                                  |  ") 
                print(" |/___________________________________________________|  ") 
                print("                                                         ")
                h = input("Press z to read the paper...   Press x to go home... ") 
                h = h.lower()
                
                if h == "z":
                  os.system("cls")
                  print("                                                         ")
                  print(" You took a look at the paper...                         ")
                  print(" And you are thinking of what to do now...               ")     
                  print("       ____________________________________________      ")
                  print("      |                                            |     ")
                  print("      |           WHO CARES FOR A WISH!            |     ")
                  print("      |                                            |     ")
                  print("      | Inside of this door you will find food,    |     ")
                  print("      | you will be able to live healthy.          |     ")
                  print("      |                                            |     ")
                  print("      | Why to go to the top when you can live     |     ")
                  print("      | as healthy as a king with all that food    |     ")
                  print("      |                                            |     ")
                  print("      | I say being healthy better than a wish!    |     ")
                  print("      |                                            |     ")
                  print("      | DO NOT LOSE THIS OPPORTUNITY!              |     ")
                  print("      |____________________________________________|     ")
                  print("                                                         ")
                  i = input("Press c to open the door... Press z to go upstairs... Press x to go home... ") 
                  i = i.lower()  
                  
                  if i == "z":
                    os.system("cls")
                    print("                                                         ")
                    print(" You finaly arrived at the rooftop...                    ") 
                    print(" You see around and all you are able to see...           ")
                    print(" is a rusty hammer in a stone pedestal and a paper...    ")
                    print("                                                         ")
                    print("      _______                _____                 ____  ")
                    print("               ________     /    /\       ________       ")  
                    print("     ______                /____/_/              ______  ")
                    print("              _____    ____\//___/_    ________          ")
                    print("      ____            |\   //     /|                     ")
                    print("           ___________| \________/ |__________           ")
                    print("          /           | |        | |          \          ")
                    print("         /            | |        | |           \         ")
                    print("        /             | |        | |            \        ")
                    print("       /              | |        | |             \       ")
                    print("      /     _____      \|________|/               \      ")
                    print("     /     /&%$@/                                  \     ")
                    print("    /     /___ /                                    \    ")
                    print("   /                                                 \   ")
                    print("  /                                                   \  ")
                    print(" /                                                     \ ")
                    print("                                                         ")
                    j = input("Press z to read the paper...   Press x to go home... ") 
                    j = j.lower()
                    
                    if j == "z":
                      os.system("cls")
                      print("                                                         ")
                      print(" You took a look at the paper...                         ")
                      print(" And you are thinking of what to do now...               ")     
                      print("       ____________________________________________      ")
                      print("      |                                            |     ")
                      print("      |               CONGRATULATIONS              |     ")
                      print("      |                                            |     ")
                      print("      | For climbing to the top you have proven... |     ")
                      print("      | worthy of taking the ancient treasure...   |     ")
                      print("      | of this tower, namely that hammer...       |     ")
                      print("      |                                            |     ")
                      print("      | To activate the power of that hammer...    |     ")
                      print("      | you need to keep it at your hands...       |     ")
                      print("      | and wait for the diety to come and to...   |     ")
                      print("      | fulfill the wish you desire...             |     ")
                      print("      |                                   CONGRATS |     ")
                      print("      |____________________________________________|     ")
                      print("                                                         ")
                      k = input("Press z to wait...  or   Press x to go home...  ") 
                      k = k.lower()  
                      
                      if k == "z":
                        os.system("cls")
                        print("                                                         ")
                        print(" You waited patienly for something to happen...          ") 
                        print(" eventually you saw a body forming next to you...        ")
                        print(" The body took the form of a human and is asking you...  ")
                        print(" to give him the wish so it can be fulfilled...          ")
                        print("                                                         ")
                        print("      _______                _____                 ____  ")
                        print("               ________        _____      ________       ")  
                        print("     ______                                      ______  ")
                        print("              _____    ____________    ________          ")
                        print("      ____            |\          /|                     ")
                        print("           ___________| \________/ |__________           ")
                        print("          /           | |        | |          \          ")
                        print("         /            | |        | |           \         ")
                        print("        /             | |        | |            \        ")
                        print("       /              | |        | |             \       ")
                        print("      /     _____      \|________|/               \      ")
                        print("     /     /&%$@/                                  \     ")
                        print("    /     /___ /                         _/^\_      \    ")
                        print("   /                      _______        /0 0\       \   ")
                        print("  /                      |TELL ME| <----- -|-         \  ")
                        print(" /                        -------         / \          \ ")
                        print("                                                         ")
                        l = input("Press z tell him your wish...   Press x to go home...") 
                        l = l.lower()
                        
                        if l == "z":
                          os.system("cls")
                          print("                                                         ")
                          print("                        CONGRATS!...                     ")
                          print(" Now you that you have proven yourself worthy...         ")
                          print(" you can tell me your desired wwish...                   ")
                          print("                                                         ")
                          End = input(" Your wish? >>  ")
                          End = End.lower()
                          
                          while End != "nothing" or End != "i wont nothing":
                            print("                                                         ")
                            print(" Sorry but i can not do that...                          ")
                            print(" Try another wish...                                     ")
                            print("                                                         ")
                            End = input(" Your wish? >>  ") 
                            End = End.lower()

                            
                              
                          os.system("cls")
                          print(" You really are something...                             ")
                          print(" Anyway now that yo want nothing you can go home...      ")
                          print("                                                         ") 
                          print("      __________              ______                     ")
                          print("                                            _________    ")
                          print("              ___________            ___________         ")
                          print("      _______                   /\         ___           ")
                          print("                               /~~\                      ")
                          print("                              /~~~~\                     ")
                          print("            _______          /~~~~~~\                    ")
                          print("       .-> |Goodbye|        /~~~~~~~~\                   ")
                          print("      /     -------        /~~~~~~~~~~\                  ")
                          print("      \                   /~~~~~~~~~~~~\                 ")
                          print("       /                 [  ___    ___  ]                ")
                          print("       \  ___            [ |_|_|  |_|_| ]                ")
                          print("         /0 0\           [     ____     ]                ")
                          print("          -|-            [    | <> |    ]                ")
                          print("          / \            [____|____|____]                ")
                          print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
                          print("                                                         ")
                          
                        elif l == "x":
                          os.system("cls")
                          print("                                                         ")
                          print(" You for some reason did not belive him so...            ")
                          print(" You went in your road and finaly ended up home...       ")
                          print("                                                         ") 
                          print("      __________              ______                     ")
                          print("                                            _________    ")
                          print("              ___________            ___________         ")
                          print("      _______                   /\         ___           ")
                          print("                               /~~\                      ")
                          print("                              /~~~~\                     ")
                          print("            _______          /~~~~~~\                    ")
                          print("       .-> |Goodbye|        /~~~~~~~~\                   ")
                          print("      /     -------        /~~~~~~~~~~\                  ")
                          print("      \                   /~~~~~~~~~~~~\                 ")
                          print("       /                 [  ___    ___  ]                ")
                          print("       \  ___            [ |_|_|  |_|_| ]                ")
                          print("         /0 0\           [     ____     ]                ")
                          print("          -|-            [    | <> |    ]                ")
                          print("          / \            [____|____|____]                ")
                          print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
                          print("                                                         ")
                          
                      elif k == "x":
                        os.system("cls")
                        print("                                                         ") 
                        print(" You thought that the challenge was a scam so...         ")
                        print(" You went in your road and finaly ended up home...       ")
                        print("                                                         ")
                        print("      __________              ______                     ")
                        print("                                            _________    ")
                        print("              ___________            ___________         ")
                        print("      _______                   /\         ___           ")
                        print("                               /~~\                      ")
                        print("                              /~~~~\                     ")
                        print("            _______          /~~~~~~\                    ")
                        print("       .-> |Goodbye|        /~~~~~~~~\                   ")
                        print("      /     -------        /~~~~~~~~~~\                  ")
                        print("      \                   /~~~~~~~~~~~~\                 ")
                        print("       /                 [  ___    ___  ]                ")
                        print("       \  ___            [ |_|_|  |_|_| ]                ")
                        print("         /0 0\           [     ____     ]                ")
                        print("          -|-            [    | <> |    ]                ")
                        print("          / \            [____|____|____]                ")
                        print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
                        print("                                                         ")
                        
                    elif j == "x":
                      os.system("cls")
                      print("                                                         ")  
                      print(" You thought that the challenge was a scam so...         ")
                      print(" You went in your road and finaly ended up home...       ")
                      print("                                                         ") 
                      print("      __________              ______                     ")
                      print("                                            _________    ")
                      print("              ___________            ___________         ")
                      print("      _______                   /\         ___           ")
                      print("                               /~~\                      ")
                      print("                              /~~~~\                     ")
                      print("            _______          /~~~~~~\                    ")
                      print("       .-> |Goodbye|        /~~~~~~~~\                   ")
                      print("      /     -------        /~~~~~~~~~~\                  ")
                      print("      \                   /~~~~~~~~~~~~\                 ")
                      print("       /                 [  ___    ___  ]                ")
                      print("       \  ___            [ |_|_|  |_|_| ]                ")
                      print("         /0 0\           [     ____     ]                ")
                      print("          -|-            [    | <> |    ]                ")
                      print("          / \            [____|____|____]                ")
                      print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
                      print("                                                         ")
                      
                  elif i == "c":
                    os.system("cls")
                    print("                                                         ")
                    print(" Blinded by the food and gluttony you went inside...     ")
                    print(" You feel a force taking you over...                     ")
                    print("  _____________________________________________________  ")
                    print(" |         |                                 |         | ")
                    print(" |         |  \( )/   \( )/   \( )/   \( )/  |         | ")
                    print(" |  \( )/  |   _|_     _|_     _|_     _|_   |  \( )/  | ")
                    print(" |   _|_   |    |       |       |       |    |   _|_   | ")
                    print(" |    |    |_________________________________|    |    | ")
                    print(" |        / __      ______________        __  \        | ")
                    print(" |       / (__    /       /\       \      __)  \       | ")
                    print(" |      /   |_  /        /  \        \   _|     \      | ")
                    print(" |     /    <) |_______ /____\_______ |  (>      \     | ")
                    print(" |    /  __    |       /      \       |   __      \    | ")
                    print(" |   /  (__    |      /        \      |   __)      \   | ")
                    print(" |  /    |_     \    /          \    /   _|         \  | ")
                    print(" | /      <)      \ /____________\ /     (>          \ | ")
                    print(" |/___________________________________________________\| ")
                    print("                                                         ")
                    print(" You were send to the third circle of hell...            ")
                    print(" Guarded by CERBERUS to make you suffer for the choice...")
                    print("                                                         ")
                    Y = input(" Press z to continue... (There is no other way...)   ")
                    Y = Y.lower()
                    
                    if Y == "z":
                      os.system("cls")
                      print("                                                         ")
                      print(" You know that you have commited a sin good for you...   ")
                      print(" But it will do to you no good that you know now...      ")
                      print(" For blood and gore the following is restricted...       ")
                      print("         ____      ____       ____     _____             ")
                      print("        /    \    /    \     |    \   |                  ")
                      print("       |         |      |    |____/   |_____             ")
                      print("       |   ___   |      |    |   \    |                  ")
                      print("        \____/    \ __ /     |    \   |_____             ")
                      print("                       __                          __    ")
                      print("  \   /\   /    /\    |  \   |\    /  ||  |\   /  /  \   ")
                      print("  \  /  \  /   /  \   |__/   | \   /  ||  | \  /  |      ")
                      print("  \  /  \  /   /__\   |  \   |  \  /  ||  | \  /  |      ")
                      print("  \ /   \  /   /  \   |  \   |  \  /  ||  | \  /  |  __  ")
                      print("   \/    \/    /  \   |  \   |   \/   ||  |  \/   \___/  ")
                      print("                                                         ")
                      print(" You will be forced to wallow in disgusting...           ")
                      print(" smelling mud and be constantly pelted...                ")
                      print(" by the endless rain, sleet, snow, and hail...           ")
                      print("                                                         ") 
                      
                    else:
                      os.system("cls")
                      print("                                                         ")
                      print(" You tried to get away but that only made it worse...    ")
                      print(" Now the force is taking you over faster...              ")
                      print(" For blood and gore the following is restricted...       ")
                      print("         ____      ____       ____     _____             ")
                      print("        /    \    /    \     |    \   |                  ")
                      print("       |         |      |    |____/   |_____             ")
                      print("       |   ___   |      |    |   \    |                  ")
                      print("        \____/    \ __ /     |    \   |_____             ")
                      print("                       __                          __    ")
                      print("  \   /\   /    /\    |  \   |\    /  ||  |\   /  /  \   ")
                      print("  \  /  \  /   /  \   |__/   | \   /  ||  | \  /  |      ")
                      print("  \  /  \  /   /__\   |  \   |  \  /  ||  | \  /  |      ")
                      print("  \ /   \  /   /  \   |  \   |  \  /  ||  | \  /  |  __  ")
                      print("   \/    \/    /  \   |  \   |   \/   ||  |  \/   \___/  ")
                      print("                                                         ")
                      print(" You will be forced to wallow in disgusting...           ")
                      print(" smelling mud and be constantly pelted...                ")
                      print(" by the endless rain, sleet, snow, and hail...           ")
                      print("                                                         ")  
                      
                  elif i == "x":
                    os.system("cls")
                    print("                                                         ") 
                    print(" You felt an uneasy feeling so...                        ")
                    print(" You went in your road and finaly ended up home...       ")
                    print("                                                         ") 
                    print("      __________              ______                     ")
                    print("                                            _________    ")
                    print("              ___________            ___________         ")
                    print("      _______                   /\         ___           ")
                    print("                               /~~\                      ")
                    print("                              /~~~~\                     ")
                    print("            _______          /~~~~~~\                    ")
                    print("       .-> |Goodbye|        /~~~~~~~~\                   ")
                    print("      /     -------        /~~~~~~~~~~\                  ")
                    print("      \                   /~~~~~~~~~~~~\                 ")
                    print("       /                 [  ___    ___  ]                ")
                    print("       \  ___            [ |_|_|  |_|_| ]                ")
                    print("         /0 0\           [     ____     ]                ")
                    print("          -|-            [    | <> |    ]                ")
                    print("          / \            [____|____|____]                ")
                    print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
                    
                elif h == "x":
                  os.system("cls")
                  print("                                                         ")
                  print(" The third floor was a bit to skechty so...              ")
                  print(" You went in your road and finaly ended up home...       ")
                  print("                                                         ") 
                  print("      __________              ______                     ")
                  print("                                            _________    ")
                  print("              ___________            ___________         ")
                  print("      _______                   /\         ___           ")
                  print("                               /~~\                      ")
                  print("                              /~~~~\                     ")
                  print("            _______          /~~~~~~\                    ")
                  print("       .-> |Goodbye|        /~~~~~~~~\                   ")
                  print("      /     -------        /~~~~~~~~~~\                  ")
                  print("      \                   /~~~~~~~~~~~~\                 ")
                  print("       /                 [  ___    ___  ]                ")
                  print("       \  ___            [ |_|_|  |_|_| ]                ")
                  print("         /0 0\           [     ____     ]                ")
                  print("          -|-            [    | <> |    ]                ")
                  print("          / \            [____|____|____]                ")
                  print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
                  print("                                                         ")
                  
              elif g == "c":
                os.system("cls")
                print("                                                         ")
                print(" Blinded by the power and wrath you went inside...       ")
                print(" You feel a force taking you over...                     ")
                print("  _____________________________________________________  ")
                print(" |         |                                 |         | ")
                print(" |         |  \( )/   \( )/   \( )/   \( )/  |         | ")
                print(" |  \( )/  |   _|_     _|_     _|_     _|_   |  \( )/  | ")
                print(" |   _|_   |  (_|     (_|     (_|     (_|    |   _|_   | ")
                print(" |  (_|    |_________________________________|  (_|    | ")
                print(" |        /         ______________            \        | ")
                print(" |       /  0     /       /\       \      0    \       | ")
                print(" |      /  )-(  /        /  \        \   )-(    \      | ")
                print(" |     /    0  |_______ /____\_______ |   0      \     | ")
                print(" |    /        |       /      \       |           \    | ")
                print(" |   /    0    |      /        \      |     0      \   | ")
                print(" |  /    )-(    \    /          \    /     )-(      \  | ")
                print(" | /      0       \ /____________\ /        0        \ | ")
                print(" |/___________________________________________________\| ")
                print("                                                         ")
                print(" You were send to the fifth circle of hell...            ")
                print(" Guarded by PHLEGYAS to make you suffer for the choice...")
                print("                                                         ")
                X = input(" Press z to continue... (There is no other way...)   ")
                X = X.lower()
                
                if X == "z":
                  os.system("cls")
                  print("                                                         ")
                  print(" You know that you have commited a sin good for you...   ")
                  print(" But it will do to you no good that you know now...      ")
                  print(" For blood and gore the following is restricted...       ")
                  print("         ____      ____       ____     _____             ")
                  print("        /    \    /    \     |    \   |                  ")
                  print("       |         |      |    |____/   |_____             ")
                  print("       |   ___   |      |    |   \    |                  ")
                  print("        \____/    \ __ /     |    \   |_____             ")
                  print("                       __                          __    ")
                  print("  \   /\   /    /\    |  \   |\    /  ||  |\   /  /  \   ")
                  print("  \  /  \  /   /  \   |__/   | \   /  ||  | \  /  |      ")
                  print("  \  /  \  /   /__\   |  \   |  \  /  ||  | \  /  |      ")
                  print("  \ /   \  /   /  \   |  \   |  \  /  ||  | \  /  |  __  ")
                  print("   \/    \/    /  \   |  \   |   \/   ||  |  \/   \___/  ")
                  print("                                                         ")
                  print(" You will tear, rend, bite, and scratch...               ")
                  print(" in an epic bare-knuckle brawl with the others there...  ")
                  print(" and even yourself for eternity...                       ")
                  print("                                                         ")
                  
                else:
                  os.system("cls")
                  print("                                                         ")
                  print(" You tried to get away but that only made it worse...    ")
                  print(" Now the force is taking you over faster...              ")
                  print(" For blood and gore the following is restricted...       ")
                  print("         ____      ____       ____     _____             ")
                  print("        /    \    /    \     |    \   |                  ")
                  print("       |         |      |    |____/   |_____             ")
                  print("       |   ___   |      |    |   \    |                  ")
                  print("        \____/    \ __ /     |    \   |_____             ")
                  print("                       __                          __    ")
                  print("  \   /\   /    /\    |  \   |\    /  ||  |\   /  /  \   ")
                  print("  \  /  \  /   /  \   |__/   | \   /  ||  | \  /  |      ")
                  print("  \  /  \  /   /__\   |  \   |  \  /  ||  | \  /  |      ")
                  print("  \ /   \  /   /  \   |  \   |  \  /  ||  | \  /  |  __  ")
                  print("   \/    \/    /  \   |  \   |   \/   ||  |  \/   \___/  ")
                  print("                                                         ")
                  print(" You will tear, rend, bite, and scratch...               ")
                  print(" in an epic bare-knuckle brawl with the others there...  ")
                  print(" and even yourself for eternity...                       ")
                  print("                                                         ")
                  
              elif g == "x":
                os.system("cls")
                print("                                                         ") 
                print(" You felt an uneasy feeling so...                        ")
                print(" You went in your road and finaly ended up home...       ")
                print("                                                         ")
                print("      __________              ______                     ")
                print("                                            _________    ")
                print("              ___________            ___________         ")
                print("      _______                   /\         ___           ")
                print("                               /~~\                      ")
                print("                              /~~~~\                     ")
                print("            _______          /~~~~~~\                    ")
                print("       .-> |Goodbye|        /~~~~~~~~\                   ")
                print("      /     -------        /~~~~~~~~~~\                  ")
                print("      \                   /~~~~~~~~~~~~\                 ")
                print("       /                 [  ___    ___  ]                ")
                print("       \  ___            [ |_|_|  |_|_| ]                ")
                print("         /0 0\           [     ____     ]                ")
                print("          -|-            [    | <> |    ]                ")
                print("          / \            [____|____|____]                ")
                print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
                print("                                                         ")
                
            elif f == "x":
              os.system("cls")
              print("                                                         ")
              print(" The second floor was a bit to skechty so...             ")
              print(" You went in your road and finaly ended up home...       ")
              print("                                                         ")
              print("      __________              ______                     ")
              print("                                            _________    ")
              print("              ___________            ___________         ")
              print("      _______                   /\         ___           ")
              print("                               /~~\                      ")
              print("                              /~~~~\                     ")
              print("            _______          /~~~~~~\                    ")
              print("       .-> |Goodbye|        /~~~~~~~~\                   ")
              print("      /     -------        /~~~~~~~~~~\                  ")
              print("      \                   /~~~~~~~~~~~~\                 ")
              print("       /                 [  ___    ___  ]                ")
              print("       \  ___            [ |_|_|  |_|_| ]                ")
              print("         /0 0\           [     ____     ]                ")
              print("          -|-            [    | <> |    ]                ")
              print("          / \            [____|____|____]                ")
              print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
              
          elif e == "c": 
            os.system("cls")
            print("                                                         ")
            print(" Blinded by the greed and the money you went inside...   ")
            print(" You feel a force taking you over...                     ")
            print("  _____________________________________________________  ")
            print(" |         |                                 |         | ")
            print(" |         |  \( )/   \( )/   \( )/   \( )/  |         | ")
            print(" |  \( )/  |   -|-     -|-     -|-     -|-   |  \( )/  | ")
            print(" |   -|-   |    |       |       |       |    |   -|-   | ")
            print(" |    |    |_________________________________|    |    | ")
            print(" |        /   _       ______________      _   \        | ")
            print(" |       /   |_)    /       /\       \   (_|   \       | ")
            print(" |      /    |_   /        /  \        \  _|    \      | ")
            print(" |     /         |_______ /____\_______ |        \     | ")
            print(" |    /   _      |       /      \       |    _    \    | ")
            print(" |   /   |_)     |      /        \      |   (_|    \   | ")
            print(" |  /    |_       \    /          \    /     _|     \  | ")
            print(" | /                \ /____________\ /               \ | ")
            print(" |/___________________________________________________\| ")
            print("                                                         ")
            print(" You were send to the fourth circle of hell...           ")
            print(" Guarded by PLUTO to make you suffer for your choices... ")
            print("                                                         ")
            Z = input(" Press z to continue... (There is no other way...)   ")
            Z = Z.lower()
            
            if Z == "z":
              os.system("cls")
              print("                                                         ")
              print(" You know that you have commited a sin good for you...   ")
              print(" But it will do to you no good that you know now...      ")
              print(" For blood and gore the following is restricted...       ")
              print("         ____      ____       ____     _____             ")
              print("        /    \    /    \     |    \   |                  ")
              print("       |         |      |    |____/   |_____             ")
              print("       |   ___   |      |    |   \    |                  ")
              print("        \____/    \ __ /     |    \   |_____             ")
              print("                       __                          __    ")
              print("  \   /\   /    /\    |  \   |\    /  ||  |\   /  /  \   ")
              print("  \  /  \  /   /  \   |__/   | \   /  ||  | \  /  |      ")
              print("  \  /  \  /   /__\   |  \   |  \  /  ||  | \  /  |      ")
              print("  \ /   \  /   /  \   |  \   |  \  /  ||  | \  /  |  __  ")
              print("   \/    \/    /  \   |  \   |   \/   ||  |  \/   \___/  ")
              print("                                                         ")
              print(" You will for eternity push a large, rolling weight...   ")
              print(" with your chest and crash it into someone guilty...     ")
              print(" of the opposing sin from the other side of the circle...")
              print("                                                         ")
              
            else:
              os.system("cls")
              print("                                                         ")
              print(" You tried to get away but that only made it worse...    ")
              print(" Now the force is taking you over faster...              ")
              print(" For blood and gore the following is restricted...       ")
              print("         ____      ____       ____     _____             ")
              print("        /    \    /    \     |    \   |                  ")
              print("       |         |      |    |____/   |_____             ")
              print("       |   ___   |      |    |   \    |                  ")
              print("        \____/    \ __ /     |    \   |_____             ")
              print("                       __                          __    ")
              print("  \   /\   /    /\    |  \   |\    /  ||  |\   /  /  \   ")
              print("  \  /  \  /   /  \   |__/   | \   /  ||  | \  /  |      ")
              print("  \  /  \  /   /__\   |  \   |  \  /  ||  | \  /  |      ")
              print("  \ /   \  /   /  \   |  \   |  \  /  ||  | \  /  |  __  ")
              print("   \/    \/    /  \   |  \   |   \/   ||  |  \/   \___/  ")
              print("                                                         ")
              print(" You will for eternity push a large, rolling weight...   ")
              print(" with your chest and crash it into someone guilty...     ")
              print(" of the opposing sin from the other side of the circle...")
              print("                                                         ")
              
          elif e == "x":
            os.system("cls")
            print("                                                         ") 
            print(" You felt an uneasy feeling so...                        ")
            print(" You went in your road and finaly ended up home...       ")
            print("                                                         ")  
            print("      __________              ______                     ")
            print("                                            _________    ")
            print("              ___________            ___________         ")
            print("      _______                   /\         ___           ")
            print("                               /~~\                      ")
            print("                              /~~~~\                     ")
            print("            _______          /~~~~~~\                    ")
            print("       .-> |Goodbye|        /~~~~~~~~\                   ")
            print("      /     -------        /~~~~~~~~~~\                  ")
            print("      \                   /~~~~~~~~~~~~\                 ")
            print("       /                 [  ___    ___  ]                ")
            print("       \  ___            [ |_|_|  |_|_| ]                ")
            print("         /0 0\           [     ____     ]                ")
            print("          -|-            [    | <> |    ]                ")
            print("          / \            [____|____|____]                ")
            print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
            print("                                                         ")
            
        elif d == "x":
          os.system("cls")
          print("                                                         ")
          print(" The first floor was a bit to skechty so...              ")
          print(" You went in your road and finaly ended up home...       ")
          print("                                                         ") 
          print("      __________              ______                     ")
          print("                                            _________    ")
          print("              ___________            ___________         ")
          print("      _______                   /\         ___           ")
          print("                               /~~\                      ")
          print("                              /~~~~\                     ")
          print("            _______          /~~~~~~\                    ")
          print("       .-> |Goodbye|        /~~~~~~~~\                   ")
          print("      /     -------        /~~~~~~~~~~\                  ")
          print("      \                   /~~~~~~~~~~~~\                 ")
          print("       /                 [  ___    ___  ]                ")
          print("       \  ___            [ |_|_|  |_|_| ]                ")
          print("         /0 0\           [     ____     ]                ")
          print("          -|-            [    | <> |    ]                ")
          print("          / \            [____|____|____]                ")
          print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
          print("                                                         ")
          
      elif c == "x":
        os.system("cls")
        print("                                                         ")
        print(" You thought that the tower was to simple so...          ")
        print(" You went in your road and finaly ended up home...       ")
        print("                                                         ")
        print("      __________              ______                     ")
        print("                                            _________    ")
        print("              ___________            ___________         ")
        print("      _______                   /\         ___           ")
        print("                               /~~\                      ")
        print("                              /~~~~\                     ")
        print("            _______          /~~~~~~\                    ")
        print("       .-> |Goodbye|        /~~~~~~~~\                   ")
        print("      /     -------        /~~~~~~~~~~\                  ")
        print("      \                   /~~~~~~~~~~~~\                 ")
        print("       /                 [  ___    ___  ]                ")
        print("       \  ___            [ |_|_|  |_|_| ]                ")
        print("         /0 0\           [     ____     ]                ")
        print("          -|-            [    | <> |    ]                ")
        print("          / \            [____|____|____]                ")
        print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
        print("                                                         ")
        
    elif b == "x":
      os.system("cls")
      print("                                                         ") 
      print(" You thought that the challenge had something off so...  ")
      print(" You went in your road and finaly ended up home...       ")
      print("                                                         ") 
      print("      __________              ______                     ")
      print("                                            _________    ")
      print("              ___________            ___________         ")
      print("      _______                   /\         ___           ")
      print("                               /~~\                      ")
      print("                              /~~~~\                     ")
      print("            _______          /~~~~~~\                    ")
      print("       .-> |Goodbye|        /~~~~~~~~\                   ")
      print("      /     -------        /~~~~~~~~~~\                  ")
      print("      \                   /~~~~~~~~~~~~\                 ")
      print("       /                 [  ___    ___  ]                ")
      print("       \  ___            [ |_|_|  |_|_| ]                ")
      print("         /0 0\           [     ____     ]                ")
      print("          -|-            [    | <> |    ]                ")
      print("          / \            [____|____|____]                ")
      print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
      print("                                                         ")  
      
  elif a == "x":
    os.system("cls")
    print("                                                         ")
    print(" Then you went in your road and finaly ended up home...  ")
    print("                                                         ")
    print("      __________              ______                     ")
    print("                                            _________    ")
    print("              ___________            ___________         ")
    print("      _______                   /\         ___           ")
    print("                               /~~\                      ")
    print("                              /~~~~\                     ")
    print("            _______          /~~~~~~\                    ")
    print("       .-> |Goodbye|        /~~~~~~~~\                   ")
    print("      /     -------        /~~~~~~~~~~\                  ")
    print("      \                   /~~~~~~~~~~~~\                 ")
    print("       /                 [  ___    ___  ]                ")
    print("       \  ___            [ |_|_|  |_|_| ]                ")
    print("         /0 0\           [     ____     ]                ")
    print("          -|-            [    | <> |    ]                ")
    print("          / \            [____|____|____]                ")
    print(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ")
    print("                                                         ")  
    
else:
  os.system("cls")
  print("                                                         ")
  print(" Why you even came if you will not play along?...        ")
  print("                                                         ")
